In [17]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
from collections import Counter
import numpy as np


In [3]:
digits = load_digits()
digits.keys()
digits_data=digits.data
digits_label=digits.target
print(digits.target_names)
print(digits.feature_names)
print(digits.DESCR)

[0 1 2 3 4 5 6 7 8 9]
['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']
.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteris

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digits_data, digits_label, test_size=0.2, random_state=32)

In [5]:
decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print("micro 평균 f1 점수: {:.16f}".format(f1_score(y_test, y_pred, average="micro")))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.89      0.94        38
           1       0.75      0.83      0.79        36
           2       0.75      0.84      0.79        32
           3       0.92      0.86      0.89        56
           4       0.85      0.90      0.88        31
           5       0.92      0.97      0.95        36
           6       0.97      0.94      0.96        34
           7       0.94      0.88      0.91        34
           8       0.88      0.78      0.82        27
           9       0.79      0.83      0.81        36

    accuracy                           0.88       360
   macro avg       0.88      0.87      0.87       360
weighted avg       0.88      0.88      0.88       360

[[34  0  2  0  0  1  0  0  1  0]
 [ 0 30  4  0  2  0  0  0  0  0]
 [ 0  2 27  0  0  1  0  0  2  0]
 [ 0  1  2 48  0  0  0  0  0  5]
 [ 0  0  0  0 28  0  1  1  0  1]
 [ 0  0  0  0  0 35  0  0  0  1]
 [ 0  0  0  0  2  0 32  0  0  0]
 [ 0  1  1

In [6]:
random_forest = RandomForestClassifier(random_state=32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print("micro 평균 f1 점수: {:.16f}".format(f1_score(y_test, y_pred, average="micro")))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.97      1.00      0.99        36
           2       0.97      1.00      0.98        32
           3       1.00      1.00      1.00        56
           4       1.00      0.97      0.98        31
           5       1.00      0.97      0.99        36
           6       1.00      1.00      1.00        34
           7       0.97      1.00      0.99        34
           8       0.96      0.89      0.92        27
           9       0.97      1.00      0.99        36

    accuracy                           0.99       360
   macro avg       0.98      0.98      0.98       360
weighted avg       0.99      0.99      0.99       360

[[38  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 56  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  1  0]
 [ 0  0  0  0  0 35  0  0  0  1]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0

In [7]:
svm_model=svm.SVC()
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print("micro 평균 f1 점수: {:.16f}".format(f1_score(y_test, y_pred, average="micro")))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       1.00      1.00      1.00        36
           2       1.00      1.00      1.00        32
           3       1.00      1.00      1.00        56
           4       1.00      0.97      0.98        31
           5       1.00      0.97      0.99        36
           6       1.00      1.00      1.00        34
           7       1.00      1.00      1.00        34
           8       1.00      1.00      1.00        27
           9       0.95      1.00      0.97        36

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360

[[38  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 56  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  1]
 [ 0  0  0  0  0 35  0  0  0  1]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0

In [8]:
sgd_model = SGDClassifier()
sgd_model.fit(X_train, y_train)
y_pred = sgd_model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print("micro 평균 f1 점수: {:.16f}".format(f1_score(y_test, y_pred, average="micro")))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       1.00      0.72      0.84        36
           2       1.00      1.00      1.00        32
           3       0.98      0.91      0.94        56
           4       0.97      0.97      0.97        31
           5       1.00      0.94      0.97        36
           6       0.97      1.00      0.99        34
           7       1.00      0.94      0.97        34
           8       0.92      0.81      0.86        27
           9       0.64      1.00      0.78        36

    accuracy                           0.93       360
   macro avg       0.95      0.93      0.93       360
weighted avg       0.95      0.93      0.93       360

[[38  0  0  0  0  0  0  0  0  0]
 [ 0 26  0  1  1  0  1  0  2  5]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 51  0  0  0  0  0  5]
 [ 0  0  0  0 30  0  0  0  0  1]
 [ 0  0  0  0  0 34  0  0  0  2]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0

In [9]:
logistic_model = LogisticRegression(solver='lbfgs', max_iter=10000).fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print("micro 평균 f1 점수: {:.16f}".format(f1_score(y_test, y_pred, average="micro")))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        38
           1       0.94      0.94      0.94        36
           2       1.00      1.00      1.00        32
           3       1.00      0.98      0.99        56
           4       1.00      0.97      0.98        31
           5       0.94      0.94      0.94        36
           6       0.97      1.00      0.99        34
           7       1.00      1.00      1.00        34
           8       0.96      0.96      0.96        27
           9       0.92      1.00      0.96        36

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.98      0.97      0.98       360

[[36  0  0  0  0  2  0  0  0  0]
 [ 0 34  0  0  0  0  1  0  0  1]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0  0  1]
 [ 0  0  0  0 30  0  0  0  1  0]
 [ 0  1  0  0  0 34  0  0  0  1]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0

In [10]:
print(confusion_matrix(y_test, y_pred))
#confusion_matrix(y_test, fake_pred)
print(classification_report(y_test, y_pred))
#print(classification_report(y_test, fake_pred))
print("micro 평균 f1 점수: {:.16f}".format(f1_score(y_test, y_pred, average="micro")))
print(accuracy_score(y_test, y_pred))#, accuracy_score(y_test, fake_pred)

[[36  0  0  0  0  2  0  0  0  0]
 [ 0 34  0  0  0  0  1  0  0  1]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0  0  1]
 [ 0  0  0  0 30  0  0  0  1  0]
 [ 0  1  0  0  0 34  0  0  0  1]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  0]
 [ 0  1  0  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0  0 36]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97        38
           1       0.94      0.94      0.94        36
           2       1.00      1.00      1.00        32
           3       1.00      0.98      0.99        56
           4       1.00      0.97      0.98        31
           5       0.94      0.94      0.94        36
           6       0.97      1.00      0.99        34
           7       1.00      1.00      1.00        34
           8       0.96      0.96      0.96        27
           9       0.92      1.00      0.96        36

    accuracy                           0.97       360
   macro avg       

성능은 svm학습모델이 제일 좋았습니다.
random_forest가 decision_tree의 단점을 개선한 버전이라 성능이 당연히 좋은 게 맞다고 생각합니다.

digit문제는 다중분류이기에 평가지표는 macro평균, weighted평균, micro평균이 있는데, 모든 샘플을 똑같이 간주하기에 micro평균이 가장 적절한 지표라고 생각합니다.